# Generated by Django 5.1.6 on 2025-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=55)),
                ("last_name", models.CharField(max_length=55)),
                ("other_name", models.CharField(blank=True, max_length=55, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("mobile_number", models.CharField(max_length=20)),
                ("photo", models.ImageField(upload_to="Author")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
